apiVersion: apps/v1
kind: Deployment
metadata:
  name: grayscale-ms
  namespace: default
  labels:
    app: grayscale-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grayscale-ms
  template:
    metadata:
      labels:
        app: grayscale-ms
    spec:
      containers:
        - name: grayscale-ms
          image: lightningboost/grayscale-ms:$COMMIT_SHA1
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-connection-secret
                  key: DATABASE_URL
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "npx prisma migrate deploy --preview-feature"]
---
apiVersion: v1
kind: Service
metadata:
  name: grayscale-ms
  labels:
    app: grayscale-ms
spec:
  ports:
    - protocol: TCP
      targetPort: 4000
      port: 4000
  type: NodePort
  selector:
    app: grayscale-ms
