version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: grayscale-db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  grayscale-ms:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: grayscale-ms
    volumes:
    - .:/app
    ports:
    - 4000:4000
    - 8181:8181
    env_file:
      - .env
    links:
      - postgres
    depends_on:
      - postgres
    command: >
      /bin/sh -c "npx prisma migrate dev --preview-feature &&
      yarn run dev"

  prisma:
    links:
      - postgres
    depends_on:
      - postgres
    container_name: prisma
    ports:
    - 5555:5555
    build:
      context: prisma
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
    - /app/prisma

volumes:
  postgres:
    name: grayscale-db
