version: '3.8'
services:
  grayscale-ms:
    container_name: grayscale-ms
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env
    links:
      - postgres
    command: >
      /bin/sh -c "npx prisma migrate resolve --preview-feature &&
      yarn run start"

  postgres:
    image: postgres:latest
    container_name: grayscale-db
    restart: always
    ports:
    - 5432:5432
    env_file:
      - .env
    volumes:
    - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: grayscale-db
