FROM node:lts-slim

WORKDIR /app

# Install Chromium
RUN apt-get update
RUN apt-get install chromium -y
RUN apt-get install yarn -y

COPY package.json /app/package.json

RUN yarn install

COPY . /app

RUN yarn run generate
